#!/bin/bash

echo "Partioning /dev/sda"
sfdisk /dev/sda < WD5000AAKX.sfdisk

echo "Creating filesystems"
mkfs.ext2 /dev/sda1
mkfs.ext4 /dev/sda3
mkswap /dev/sda2
swapon /dev/sda2

echo "Loading MBR"
dd if=WD5000AAKX.mbr of=/dev/sda bs=512 count=1

echo "Mounting"
mount /dev/sda3 /mnt/gentoo
mkdir /mnt/gentoo/boot
mount /dev/sda1 /mnt/gentoo/boot

