#!/bin/bash

echo "Downloading stage tarball"
cd /mnt/gentoo
wget http://rio.objectos.com.br/gentoo/servidor-20130802.tar.bz2

echo "Extracting"
tar xjpf servidor-*.tar.bz2

echo "Unmount"
cd /
umount /mnt/gentoo/boot
umount /mnt/gentoo

echo "Done!"
