#!/bin/bash
#version="kepler-upgrade-20131009"
#version="kepler-jee-SR1-20131009"
version="jee-kepler-SR1-20131009"
server="http://localhost/users"
f_eclipse="eclipse-jee-kepler-SR1-linux-gtk-x86_64.tar.gz"
f_jdk="openjdk-6-src-b27-26_oct_2012.tar.gz" 
downloads="$f_eclipse $f_jdk"
work="/tmp/eclipse"
kdo="$HOME/kdo"
jdk6="$kdo/jdk6"
target="$tmp/eclipse"

preconditions() {
  if [ ! -f $HOME/.rio ]; then
    echo "Arquivo de configuração ~/.rio não encontrado!"
    echo "Crie um arquivo ~/.rio com o conteúdo (notar as aspas):"
    echo "EMAIL=\"seu-email@objectos.com.br\""
    echo "NOME=\"Seu nome\""
    exit 1 
  fi
  source $HOME/.rio
  echo "email=$EMAIL"
  echo "nome=$NOME"
}

workdir_prepare() {
  echo "[INFO] Criando diretório de trabalho"
  rm -rf $work
  mkdir -p $work/wget
  mkdir -p $work/tmp
}

download() {
  echo "[INFO] Baixando arquivos. Aguarde..."
  
  for f in $downloads 
  do
    wget -nv -P $work/wget $server/$f
  done
}

unpack() {
  local user=`whoami`

  echo "[INFO] Descompactando"
  tar xzf $work/wget/$f_eclipse -C $work/tmp

  echo "[INFO] Código fonte JDK (LER CÓDIGOS!!!)"
  mkdir $work/tmp/jdk6
  tar xzf $work/wget/$f_jdk -C $work/tmp/jdk6

  echo "[INFO] Corrige permissões"
  chown -R $user. $work/tmp
}

move() {
  echo "[INFO] Movendo arquivos"
  rm -rf $target
  mv $work/tmp/eclipse $target
  rm -rf $jdk6
  mv $work/tmp/jdk6/jdk/src/share/classes $jdk6
}

config() {
  echo "[INFO] Arquivos de config"
  cp -a home $work

  home=$(echo "$HOME" | sed 's/\//\\\//g')

  find $work/home -type f -exec sed -i "s/{{home}}/$home/g" {} \;
  find $work/home -type f -exec sed -i "s/{{email}}/$EMAIL/g" {} \;
  find $work/home -type f -exec sed -i "s/{{nome}}/$NOME/g" {} \;

  tar cf - -C $work/home . | tar xf - -C $HOME
}

preconditions
workdir_prepare
download
unpack
move
config

echo "[INFO] Eclipse instalado."
echo "[INFO] Siga com a configuração em https://github.com/objectos/rio/wiki/Eclipse"
